# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://adi-69.github.io"
baseurl: "/endermc"
siteIcon: https://media.discordapp.net/attachments/853079475017089054/961609589470666772/Glitch-Purple.avi-Full-Size.gif
siteYear: 2023
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: Ender MC
serverDescription: A Minecraft server where we have lots of fun!
serverIP: play.endermc.fun
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/5DFZyTKfpw
discordServerID: 855091709209608222
discordChannelID: 1059879608348053674


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
